name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      BASE_URL: https://keila.io
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: "Build & Deploy"
        run: |
          # Install Node
          sudo apt update && sudo apt install nodejs

          # Install packages and build
          npm ci
          npm run build

          # Add SSH key
          mkdir ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/*

          # Deploy
          DEPLOY_TARGET=${{ secrets.DEPLOY_TARGET }} npm run deploy
